<a href="https://colab.research.google.com/github/FilipeSCampos/AnaliseEstatisticaDados/blob/main/AnaliseAula4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
Row = 10
Column = 5
matrix = []
for row in range(Row):
    a = []
    for column in range(Column):
        a.append(int(random.randint(1,5)))
    matrix.append(a)
print(matrix)

[[4, 5, 4, 4, 4], [3, 3, 4, 1, 3], [3, 2, 1, 4, 2], [3, 2, 3, 4, 3], [5, 1, 5, 2, 5], [4, 5, 1, 1, 2], [1, 4, 3, 3, 3], [2, 2, 5, 1, 3], [1, 4, 2, 4, 4], [3, 5, 5, 1, 2]]


In [51]:
import random
import numpy as np
import pandas as pd
import statistics
import math

In [15]:
df = pd.DataFrame(matrix, columns=['1ª','2ª','3ª','4ª','5ª'])
display(df)

1ª  2ª  3ª  4ª  5ª
0   4   5   4   4   4
1   3   3   4   1   3
2   3   2   1   4   2
3   3   2   3   4   3
4   5   1   5   2   5
5   4   5   1   1   2
6   1   4   3   3   3
7   2   2   5   1   3
8   1   4   2   4   4
9   3   5   5   1   2

In [32]:
x = []
for column in df:
    a = (df[column].std(ddof = 0))
    x.append(a)
print(x)

[1.2206555615733703, 1.4177446878757827, 1.4866068747318506, 1.3601470508735443, 0.9433981132056604]


In [37]:
media = np.array(x)
print(media.mean())

1.2857104576520415


In [39]:
media_pond = (x[0] * 2 + x[1] * 3 + x[2] * 1 + x[3] * 2.5 + x[4] * 3) / 10.5
print(media_pond)

1.372544193172074


In [57]:
z = 1.96
mstd = media
E = 0.2

n = (z * media_pond / E) ** 2
n.round()

181.0

In [65]:

import math
import numpy as np
import random

numrespond=1000 # PODE afetar o tamanho MÍNIMO da amostra; numquest=5 # NÃO afeta o tamanho MÍNIMO da amostra.
numquest=5
E=0.2
escalamax=5 # AFETA o tamanho MÍNIMO da amostra

matriz = np.zeros((numrespond, numquest))
mediaq =np.empty(numquest)

somaq =np.empty(numrespond)
somaquad =np.empty(numrespond)

var =np.empty(numquest)
desvio =np.empty(numquest)
arraysomaq =np.empty(numrespond)
somarespostas = np.zeros(numrespond)
somadasvar = 0
varianciasomaresp = 0
tamanhon = 0

for j in range(numquest):
  for i in range(numrespond):
    numaleatorio=round(random.random()*escalamax,0)
    correcao=0
    if numaleatorio==0:
      correcao=1
    if numaleatorio==escalamax:
      correcao=0
    matriz[i][j]=numaleatorio+correcao

for j in range(numquest):
  somaq=0
  somaquad=0

  for linha in range(numrespond):
    somaq=somaq+matriz[linha,j]

  mediaq[j]=somaq/numrespond

  for linha in range(numrespond):
    somaquad=somaquad+(matriz[linha,j]-mediaq[j])**2

    var[j]=somaquad/(numrespond-1)
    desvio[j]=math.sqrt(var[j])
    somadasvar+=var[j]

for linha in range(numrespond):
  for j in range(numquest):
    somarespostas[linha]=somarespostas[linha]+matriz[linha,j]

varianciasomaresp=(np.std(somarespostas, ddof=0))**2
mediadesvio=np.mean(desvio)
tamanhon=(1.96*mediadesvio/E)**2

print(matriz)
print(round(tamanhon,0))

[[1. 5. 2. 1. 1.]
 [5. 1. 5. 2. 5.]
 [1. 1. 2. 1. 5.]
 ...
 [1. 2. 4. 1. 5.]
 [2. 4. 2. 1. 2.]
 [2. 1. 3. 5. 3.]]
177.0


# Intervalo de Classes


In [69]:
dolar = [5.16, 5.2323, 5.284, 5.2403, 5.2159, 5.1241, 5.1218, 5.0491, 5.1121, 5.1017, 5.0919, 5.1334, 5.1779, 5.1767, 5.1955, 5.1703, 5.1024, 5.1044, 5.1167, 5.0897, 5.0423, 5.0611, 5.1784]

dados = pd.DataFrame({'Cotação': dolar})

classes = [5.10, 5.15, 5.20, 5.25]

frequencia = pd.cut(dados['Cotação'], bins = classes).value_counts().sort_index()

print('Distribuição de frequencia')
display(frequencia)

Distribuição de frequencia


(5.1, 5.15]    8
(5.15, 5.2]    6
(5.2, 5.25]    3
Name: Cotação, dtype: int64

In [82]:
y = np.array(frequencia)

for i in range(3):
  print(y[i]/len(dolar))



0.34782608695652173
0.2608695652173913
0.13043478260869565


In [83]:
len(dolar)

23